sudo: false
language: ruby
rvm:
  - 2.1.1
  - 2.2.2
  - 2.2.3
  - 2.2.4
  - 2.2.5
  - 2.3.0
  - 2.3.1
before_install: gem install bundler -v 1.12.5
addons:
  code_climate:
    repo_token: 4415bcfcf6ba75e0dfcc5a3a14277803c8ee9401c84b3dbd65d1aa11004d7321
